load("@rules_shell//shell:sh_binary.bzl", "sh_binary")

package(default_visibility = ["//visibility:public"])

exports_files([
    "pyinstaller.sh",
    "autopatch-runtime.sh",
    "prune-oss-cad-suite.sh",
])

sh_binary(
    name = "pyinstaller",
    srcs = ["pyinstaller.sh"],
)

filegroup(
    name = "autopatch_runtime",
    srcs = ["autopatch-runtime.sh"],
)
